@extends('layouts.admin')
@section('title', $project->exists ? 'Edit project' : 'Add project')
@section('content')
<div><div class="flex items-center gap-2"><a class="text-xs font-bold text-slate-400 hover:text-violet-600" href="{{ route('admin.projects.index') }}">Projects</a><x-icon name="chevron-right" class="size-3 text-slate-300" /><span class="text-xs font-bold text-violet-600">{{ $project->exists ? 'Edit' : 'New' }}</span></div><h1 class="admin-title mt-2">{{ $project->exists ? 'Edit '.$project->title : 'Create a project' }}</h1></div>
<form method="POST" action="{{ $project->exists ? route('admin.projects.update', $project) : route('admin.projects.store') }}" class="mt-8 grid gap-6 xl:grid-cols-[1fr_340px]">@csrf @if($project->exists) @method('PUT') @endif
    <section class="admin-card p-6"><div class="grid gap-5 sm:grid-cols-2"><div><label class="form-label">Project title</label><input class="form-input" name="title" value="{{ old('title', $project->title) }}" required></div><div><label class="form-label">Slug <span class="font-normal text-slate-400">(optional)</span></label><input class="form-input" name="slug" value="{{ old('slug', $project->slug) }}"></div><div><label class="form-label">Category</label><input class="form-input" name="category" value="{{ old('category', $project->category) }}" placeholder="Web application"></div><div><label class="form-label">Display order</label><input class="form-input" type="number" name="sort_order" min="0" value="{{ old('sort_order', $project->sort_order ?? 0) }}" required></div><div class="sm:col-span-2"><label class="form-label">Summary</label><textarea class="form-input min-h-24" name="summary" required>{{ old('summary', $project->summary) }}</textarea></div><div class="sm:col-span-2"><label class="form-label">Detailed case study</label><textarea class="form-input min-h-44" name="description">{{ old('description', $project->description) }}</textarea></div><div class="sm:col-span-2"><label class="form-label">Technologies <span class="font-normal text-slate-400">(comma separated)</span></label><input class="form-input" name="technologies_text" value="{{ old('technologies_text', implode(', ', $project->technologies ?? [])) }}" placeholder="Laravel, Tailwind CSS, MySQL"></div><div><label class="form-label">Live project URL</label><input class="form-input" type="url" name="project_url" value="{{ old('project_url', $project->project_url) }}" placeholder="https://"></div><div><label class="form-label">GitHub URL</label><input class="form-input" type="url" name="github_url" value="{{ old('github_url', $project->github_url) }}" placeholder="https://github.com/"></div></div></section>
    <aside class="space-y-6"><section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Visibility</h2><div class="mt-5 space-y-4"><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Published</span><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $project->exists ? $project->is_published : true)) class="size-5 rounded border-slate-300 text-violet-600"></label><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Featured project</span><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $project->exists ? $project->is_featured : true)) class="size-5 rounded border-slate-300 text-violet-600"></label></div><button class="admin-btn mt-6 w-full" type="submit"><x-icon name="save" class="size-4" />{{ $project->exists ? 'Save changes' : 'Create project' }}</button></section>@if($project->exists)<section class="admin-card border-rose-100 p-6"><p class="font-extrabold text-slate-950">Delete project</p><p class="mt-2 text-xs leading-5 text-slate-500">This permanently removes the project from your portfolio.</p><button form="delete-project" class="mt-4 text-xs font-extrabold text-rose-600" type="submit">Delete permanently</button></section>@endif</aside>
</form>
@if($project->exists)<form id="delete-project" method="POST" action="{{ route('admin.projects.destroy', $project) }}" data-confirm="Delete this project permanently?">@csrf @method('DELETE')</form>@endif
@endsection
