@extends('layouts.admin')
@section('title', $service->exists ? 'Edit service' : 'Add service')
@section('content')
<div><div class="flex items-center gap-2"><a class="text-xs font-bold text-slate-400 hover:text-violet-600" href="{{ route('admin.services.index') }}">Services</a><x-icon name="chevron-right" class="size-3 text-slate-300" /><span class="text-xs font-bold text-violet-600">{{ $service->exists ? 'Edit' : 'New' }}</span></div><h1 class="admin-title mt-2">{{ $service->exists ? 'Edit '.$service->title : 'Create a service' }}</h1></div>
<form method="POST" action="{{ $service->exists ? route('admin.services.update', $service) : route('admin.services.store') }}" class="mt-8 grid gap-6 xl:grid-cols-[1fr_340px]">@csrf @if($service->exists) @method('PUT') @endif
    <section class="admin-card p-6"><div class="grid gap-5 sm:grid-cols-2"><div><label class="form-label">Title</label><input class="form-input" name="title" value="{{ old('title', $service->title) }}" required></div><div><label class="form-label">Slug <span class="font-normal text-slate-400">(auto-generated if empty)</span></label><input class="form-input" name="slug" value="{{ old('slug', $service->slug) }}"></div><div><label class="form-label">Icon</label><select class="form-input" name="icon">@foreach(['code'=>'Code','terminal'=>'Terminal','network'=>'Network','server'=>'Server','search'=>'Search','megaphone'=>'Marketing','briefcase'=>'Briefcase'] as $value=>$label)<option value="{{ $value }}" @selected(old('icon', $service->icon ?: 'code') === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="form-label">Display order</label><input class="form-input" type="number" name="sort_order" min="0" value="{{ old('sort_order', $service->sort_order ?? 0) }}" required></div><div class="sm:col-span-2"><label class="form-label">Summary</label><textarea class="form-input min-h-24" name="summary" required>{{ old('summary', $service->summary) }}</textarea></div><div class="sm:col-span-2"><label class="form-label">Description</label><textarea class="form-input min-h-36" name="description">{{ old('description', $service->description) }}</textarea></div><div class="sm:col-span-2"><label class="form-label">Features <span class="font-normal text-slate-400">(one per line)</span></label><textarea class="form-input min-h-40" name="features_text">{{ old('features_text', implode("\n", $service->features ?? [])) }}</textarea></div></div></section>
    <aside class="space-y-6"><section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Visibility</h2><div class="mt-5 space-y-4"><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Published</span><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $service->exists ? $service->is_published : true)) class="size-5 rounded border-slate-300 text-violet-600"></label><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Featured on home</span><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $service->exists ? $service->is_featured : true)) class="size-5 rounded border-slate-300 text-violet-600"></label></div><button class="admin-btn mt-6 w-full" type="submit"><x-icon name="save" class="size-4" />{{ $service->exists ? 'Save changes' : 'Create service' }}</button></section>@if($service->exists)<section class="admin-card border-rose-100 p-6"><p class="font-extrabold text-slate-950">Delete service</p><p class="mt-2 text-xs leading-5 text-slate-500">This permanently removes the service from your website.</p><button form="delete-service" class="mt-4 text-xs font-extrabold text-rose-600" type="submit">Delete permanently</button></section>@endif</aside>
</form>
@if($service->exists)<form id="delete-service" method="POST" action="{{ route('admin.services.destroy', $service) }}" data-confirm="Delete this service permanently?">@csrf @method('DELETE')</form>@endif
@endsection
