@extends('layouts.admin')
@section('title', 'Edit '.$page->title)
@section('content')
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div class="flex items-center gap-2"><a class="text-xs font-bold text-slate-400 hover:text-violet-600" href="{{ route('admin.pages.index') }}">Pages</a><x-icon name="chevron-right" class="size-3 text-slate-300" /><span class="text-xs font-bold text-violet-600">{{ $page->title }}</span></div><h1 class="admin-title mt-2">Edit {{ $page->title }}</h1><p class="admin-subtitle">Update page copy and search appearance.</p></div><span class="status-pill status-live self-start">Protected system page</span></div>
<form method="POST" action="{{ route('admin.pages.update', $page) }}" class="mt-8 grid gap-6 xl:grid-cols-[1fr_340px]">@csrf @method('PUT')
    <div class="space-y-6">
        <section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Page content</h2><div class="mt-6 grid gap-5 sm:grid-cols-2"><div><label class="form-label">Page title</label><input class="form-input" name="title" value="{{ old('title', $page->title) }}" required></div><div><label class="form-label">Eyebrow</label><input class="form-input" name="eyebrow" value="{{ old('eyebrow', $page->eyebrow) }}" placeholder="Short context label"></div><div class="sm:col-span-2"><label class="form-label">Introduction</label><textarea class="form-input min-h-24" name="excerpt">{{ old('excerpt', $page->excerpt) }}</textarea></div><div class="sm:col-span-2"><label class="form-label">Main content <span class="font-normal text-slate-400">(basic HTML supported)</span></label><textarea class="form-input min-h-80 font-mono text-xs leading-6" name="content">{{ old('content', $page->content) }}</textarea></div></div></section>
        <section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Search appearance</h2><p class="mt-1 text-xs text-slate-500">Control how the page can appear in search results.</p><div class="mt-6 space-y-5"><div><label class="form-label">SEO title</label><input class="form-input" name="meta_title" maxlength="160" value="{{ old('meta_title', $page->meta_title) }}"></div><div><label class="form-label">Meta description</label><textarea class="form-input min-h-24" maxlength="300" name="meta_description">{{ old('meta_description', $page->meta_description) }}</textarea></div><div class="rounded-2xl border border-slate-200 p-5"><p class="text-sm font-semibold text-blue-700">{{ $page->meta_title ?: $page->title }}</p><p class="mt-1 text-xs text-emerald-700">{{ url($page->slug === 'home' ? '/' : '/'.$page->slug) }}</p><p class="mt-2 text-xs leading-5 text-slate-500">{{ $page->meta_description ?: $page->excerpt }}</p></div></div></section>
    </div>
    <aside class="space-y-6">
        <section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Publish</h2><div class="mt-5 space-y-4"><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Published</span><input type="checkbox" checked disabled class="size-5 rounded text-violet-600"><input type="hidden" name="is_published" value="1"></label><label class="flex items-center justify-between gap-4 text-sm font-bold text-slate-700"><span>Show in navigation</span><input type="checkbox" name="show_in_navigation" value="1" @checked(old('show_in_navigation', $page->show_in_navigation)) class="size-5 rounded border-slate-300 text-violet-600"></label><div><label class="form-label">Menu order</label><input class="form-input" type="number" name="sort_order" min="0" max="999" value="{{ old('sort_order', $page->sort_order) }}" required></div></div><button class="admin-btn mt-6 w-full" type="submit"><x-icon name="save" class="size-4" />Save changes</button></section>
        <section class="rounded-2xl border border-violet-100 bg-violet-50 p-5"><p class="text-xs font-extrabold uppercase tracking-wider text-violet-700">System protection</p><p class="mt-2 text-xs leading-6 text-violet-700/75">This default page cannot be deleted or unpublished, which keeps the website structure stable.</p></section>
    </aside>
</form>
@endsection
