@extends('layouts.admin')
@section('title', 'Message from '.$message->name)
@section('content')
<div class="flex items-center gap-2"><a class="text-xs font-bold text-slate-400 hover:text-violet-600" href="{{ route('admin.messages.index') }}">Inbox</a><x-icon name="chevron-right" class="size-3 text-slate-300" /><span class="text-xs font-bold text-violet-600">Message</span></div>
<div class="mt-5 grid gap-6 xl:grid-cols-[1fr_330px]">
    <article class="admin-card p-7 sm:p-9"><div class="flex flex-col gap-5 border-b border-slate-100 pb-7 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-extrabold uppercase tracking-[.15em] text-violet-600">{{ $message->service ?: 'General enquiry' }}</p><h1 class="mt-3 text-2xl font-extrabold tracking-tight text-slate-950">{{ $message->subject }}</h1><p class="mt-2 text-sm text-slate-500">From <strong class="text-slate-700">{{ $message->name }}</strong> · {{ $message->created_at->format('F j, Y \a\t g:i A') }}</p></div><span class="status-pill status-draft">Read</span></div><div class="whitespace-pre-line py-8 text-[15px] leading-8 text-slate-700">{{ $message->message }}</div><a href="mailto:{{ $message->email }}?subject=Re:%20{{ urlencode($message->subject) }}" class="admin-btn"><x-icon name="mail" class="size-4" />Reply by email</a></article>
    <aside class="space-y-6"><section class="admin-card p-6"><h2 class="font-extrabold text-slate-950">Sender details</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-xs font-bold text-slate-400">Name</dt><dd class="mt-1 font-bold text-slate-700">{{ $message->name }}</dd></div><div><dt class="text-xs font-bold text-slate-400">Email</dt><dd class="mt-1 break-all font-bold text-slate-700">{{ $message->email }}</dd></div><div><dt class="text-xs font-bold text-slate-400">Phone</dt><dd class="mt-1 font-bold text-slate-700">{{ $message->phone ?: 'Not provided' }}</dd></div></dl></section><section class="admin-card border-rose-100 p-6"><p class="font-extrabold text-slate-950">Delete message</p><p class="mt-2 text-xs leading-5 text-slate-500">This action cannot be undone.</p><form method="POST" action="{{ route('admin.messages.destroy', $message) }}" class="mt-4" data-confirm="Delete this message permanently?">@csrf @method('DELETE')<button class="text-xs font-extrabold text-rose-600" type="submit">Delete permanently</button></form></section></aside>
</div>
@endsection
